version: 2

project_name: sareq

before:
  hooks:
    - go mod tidy

builds:
  - id: linux
    main: ./main.go
    binary: sareq
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/im-varun/sareq/internal/release.versionString={{.Tag}}

  - id: darwin
    main: ./main.go
    binary: sareq
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/im-varun/sareq/internal/release.versionString={{.Tag}}

  - id: windows
    main: ./main.go
    binary: sareq
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/im-varun/sareq/internal/release.versionString={{.Tag}}

archives:
  - id: linux
    ids: [linux]
    formats: ["tar.gz"]
    name_template: "{{.ProjectName}}-{{.Tag}}-{{.Os}}-{{.Arch}}"
    files:
      - LICENSE
      - README.md
      # - CHANGELOG.md
      - docs/*

  - id: darwin
    ids: [darwin]
    formats: ["tar.gz"]
    name_template: "{{.ProjectName}}-{{.Tag}}-{{.Os}}-{{.Arch}}"
    files:
      - LICENSE
      - README.md
      # - CHANGELOG.md
      - docs/*

  - id: windows
    ids: [windows]
    formats: ["zip"]
    name_template: "{{.ProjectName}}-{{.Tag}}-{{.Os}}-{{.Arch}}"
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - docs/*

checksum:
  name_template: "{{.ProjectName}}-{{.Tag}}-{{.Os}}-{{.Arch}}.{{.Algorithm}}"
  split: true

changelog:
  disable: true
  